[package]
name = "pathaid"
version = "0.1.0"
edition = "2021"
authors = ["Joel Gruselius <github.com/jgruselius>"]
description = "Simple tool to validate the PATH environment variable"

[dependencies]
anyhow = "*"
colored = "2"
clap = "4"

[profile.release]
lto = true
strip = true
opt-level = "s"
